version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  assignees:
  - a0viedo
  ignore:
  - dependency-name: serverless
    versions:
    - 2.20.1
    - 2.21.1
    - 2.22.0
    - 2.23.0
    - 2.25.2
    - 2.28.0
    - 2.28.7
    - 2.29.0
    - 2.30.3
    - 2.31.0
    - 2.33.1
    - 2.35.0
  - dependency-name: date-fns
    versions:
    - 2.16.1
    - 2.17.0
    - 2.19.0
    - 2.20.1
  - dependency-name: aws-sdk
    versions:
    - 2.831.0
    - 2.834.0
    - 2.839.0
    - 2.843.0
    - 2.848.0
    - 2.853.0
    - 2.858.0
    - 2.863.0
    - 2.868.0
    - 2.874.0
    - 2.879.0
    - 2.884.0
